### ISSUE TITLE
Startup Crash with latest version

### ISSUE THREAD

**Issue by angelnc1989** [T145/tbone#2]
## Problem Details
https://pastebin.com/um4mB0SE

## Environment

- OS: Windows 10 64-bit
- Full Forge version: 14.23.5.2838
- Mod version: 11.4.7

**Comment by angelnc1989** [comment]
I'm still crashing with the 1.5.0 version.
https://pastebin.com/ME5vuGMc

**Comment by T145** [comment]
@angelnc1989 Be sure you've uninstalled FastWorkbench, FastFurnace & Responsive Beacons. If you have Quick Leaf Decay or some other variant uninstall that in favor of my feature. Someone else shared a similar error and its due to leaving any variation of the embedded mods present.
