### ISSUE TITLE
Cross Mod Bug with CustomNPCs

### ISSUE THREAD

**Issue by TGDesigner** [T145/tbone#3]
## Problem Details

There seems to be an issue when both CustomNPCs and Tbone are both installed
When both mods are installed furnaces no longer function correctly.
Instead of outputting stacks of smelted items, only one item can be in the output at a time and so long as the output has any item in it, it will continue to consume fuel but no longer smelt further items.

## Environment

- OS: Windows 10 64-bit
- Full Forge version: Forge 14.23.5.2838 (Minecraft 1.12.2) 
- Mod version: Tbone 1.5.0+mc1.12.2
- Other Mod Version: CustomNPCs_1.12.2(30Jan19)

**Comment by T145** [comment]
I haven't made *any* changes to the FastFurnace furnace tile entity, so this is likely just a core problem w/ that mod. I'll look into it, but in the meantime you can disable `TFurnace` from the `Mods` section.

**Comment by TGDesigner** [comment]
Thanks for the quick reply. I figured it was likely CustomNPC, but didn't have the code knowledge to exactly diagnose the issue, so I decided to report to both mod authors.

That being said, when I go into the Mods section of Forge, there is no option to disable TFurnace, or any of the other mods in TBone.

**Comment by benserwa** [comment]
I just had the most recent version of this mod crash my pack when it also had FastFurnace and FastWorkbench in. Seems like the same bug but yeah, newest version crashes the pack if those are in. I'll just get rid of them and hope your solution is better!

**Comment by T145** [comment]
@benserwa Uninstalling those is listed as a requirement: [https://www.curseforge.com/minecraft/mc-mods/tbone](https://www.curseforge.com/minecraft/mc-mods/tbone)

@TGDesigner The TFurnace mod [should be able to be disabled](https://github.com/T145/tbone/blob/master/src/main/java/T145/tbone/core/TFurnace.java#L21). As for CustomNPCs, is there an option to disable some feature that may affect furnaces?

**Comment by TGDesigner** [comment]
Strange. when I'm on the mod screen in Forge there's no disable button on TFurnace. I'm at a loss for what the issue is.

![Capture](https://user-images.githubusercontent.com/47574184/61421412-79590400-a8b3-11e9-9e94-05c35a1509f4.JPG)

Edit: I looked at the config for CustomNPCs. No options to disable anything involving furnace interactions.

**Comment by T145** [comment]
Integrated mods have been removed as of the latest version, so you can go back to using FastWorkbench & FastFurnace w/ no issues.

**Comment by T145** [comment]
Btw, if you're using FastFurnace, toggling its only config option to false should fix your problem here.

**Comment by Phorcis** [comment]
I still have this problem, toggling config option to false doesnt help
Forge 28.0.2844
TBone 1.6.8
FastFurnace 1.3.1
No TFurnace in the list of mods
