### ISSUE TITLE
FastXYZ integration is opaque and leads to confusion & frustration

### ISSUE THREAD

**Issue by noobanidus** [T145/tbone#4]
As I said in my comment on Metal Chests, the recent change to this mod resulted in me spending several hours attempting to work out which of the recently updated mods was the cause -- as it took a good 10 minutes to actually load the pack, performing a pseudo-binary search was the only method I found.

The error itself is extremely obscure and Googling it gives no actual relevant results.

Considering this is a library mod depended on for Metal Chests, I really think you have gone completely beyond the scope of the mod. Forcing people to uninstall other mods simply because you now implement their functionality is annoying to say the least, not to mention the fact that most people running this combination of mods won't even be aware of what's causing it.

I would like to suggest/recommend that, instead of causing a crash whenever the other mods are installed, perform some sort of check to see whether FastWorkbench, FastFurnace or any of the conflicting mods are installed, and either:

a) Don't perform your changes and simply let the other mods take over.
or b) Cause a specific crash with an explanation of what the issue is and how the player needs to remove the conflicting mods.

I'd also recommend marking your mod as conflicting with FastWorkbench, etc, on CurseForge. 

I'll still continue to use MetalChests as it is superior to IronChests (and doesn't copy items for every single attempted insert, including setting up additional capabilities), but this experience has left a bitter taste in my mouth as I would've easily liked to have spent the time spent on tracking down the cause on other things.

**Comment by T145** [comment]
This update was intended to experiment w/ Metal Transport. The mod is in beta, and therefore if anything bad happened I wanted to have the ability to make changes as I want, & then worry about reporting things later. The update was not required for Metal Chests, as the previous version worked with it. There's a config option to disable update notifications if you prefer not to see the prompt. My thought process was that people would use this only alongside Metal Transport, which was inaccurate. I'll be making PRs to the other repos for any important changes I made. Regardless, I laid out all of the changes on the CurseForge, so those hours you spent aren't on me. I'll be unpackaging anything integrated and lay them out as explicit dependencies.

**Comment by noobanidus** [comment]
> Regardless, I laid out all of the changes on the CurseForge, so those hours you spent aren't on me.

This is wrong, surely you realise? I updated 10-15 mods in one go and then started experiencing an obscure error. There was no way for me to know that your mod was the one causing it, therefore there was no way for me to find that it was listed on your CurseForge ***until*** I actually found the mod that was the problem.

So, sorry, this is definitely on you. You can't make game-breaking interactions like this that don't result in a clear crash identifying the responsible mod.

That's why I suggested checking for potential conflicting mods being installed and triggering a less obscure error message that actually identifies the issue.

**Comment by T145** [comment]
I understand the frustration, believe me. But what mostly removes the anger is reading the changelogs of everything you update. When you batch update like that, knowing what's changed is essential. I've prepared countless modpacks for my friends and I ever since 1.2.5, so I can empathize. The changes were in poor taste, as my thought process for what I thought people would do and what they did do obviously didn't match up. If you want your pack to work perfectly, just go back to the prior version of TBone to use Metal Chests. Metal Transport isn't ready for full modpack usage yet, which I thought would be apparent by labeling it as a "beta." As stated, the changes are being undone, and I'm truly sorry for the frustration.
